apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: db-access
  title: Quản lý truy cập CSDL

  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: website
  lifecycle: production
  owner: ai