-- =====================================================================
-- [DEV-OVERRIDE] H2-compatible DDL translated from V1__schema.sql + V4__replace_access_registration.sql
-- Original Oracle DDL is in src/main/resources/db/oracle/V1__schema.sql
-- To restore Oracle: remove this file and set ddl-auto=create in application.yml
-- =====================================================================

-- ============================ DANH MUC ============================

CREATE TABLE unit (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(50)  NOT NULL,
    name   VARCHAR(200) NOT NULL,
    active BOOLEAN      DEFAULT TRUE NOT NULL,
    CONSTRAINT uk_unit_code UNIQUE (code)
);

CREATE TABLE department (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(50)  NOT NULL,
    name    VARCHAR(200) NOT NULL,
    unit_id BIGINT       NOT NULL,
    active  BOOLEAN      DEFAULT TRUE NOT NULL
);

CREATE TABLE information_system (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(50)  NOT NULL,
    name                VARCHAR(200) NOT NULL,
    owner_unit_id       BIGINT,
    owner_department_id BIGINT,
    active              BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT uk_infosys_code UNIQUE (code)
);

CREATE TABLE database_catalog (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id     BIGINT       NOT NULL,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(200) NOT NULL,
    owner_unit_id BIGINT,
    active        BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE access_right_catalog (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR(50)  NOT NULL,
    name   VARCHAR(150) NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT uk_right_code UNIQUE (code)
);

CREATE TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(300),
    CONSTRAINT uk_role_code UNIQUE (code)
);

CREATE TABLE work_shift (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_no   INT          NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    start_hour INT          NOT NULL,
    end_hour   INT          NOT NULL,
    label      VARCHAR(50),
    active     BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT uk_shift_no UNIQUE (shift_no)
);

-- ============================ NGUOI DUNG / PHAN QUYEN ============================

CREATE TABLE app_user (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR(100) NOT NULL,
    full_name          VARCHAR(200),
    mobile             VARCHAR(30),
    email              VARCHAR(200),
    unit_id            BIGINT,
    department_id      BIGINT,
    signature_image_id BIGINT,
    status             VARCHAR(20) DEFAULT 'ACTIVE',
    CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE user_role (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT  NOT NULL,
    role_id       BIGINT  NOT NULL,
    unit_id       BIGINT,
    department_id BIGINT,
    system_id     BIGINT,
    database_id   BIGINT,
    active        BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE signature_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    content_type VARCHAR(100),
    data         BLOB
);

CREATE TABLE user_totp (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    secret       VARCHAR(64) NOT NULL,
    enabled      BOOLEAN DEFAULT FALSE NOT NULL,
    created_at   TIMESTAMP,
    confirmed_at TIMESTAMP,
    CONSTRAINT uk_totp_user UNIQUE (user_id)
);

-- ============================ PHIEU YEU CAU ============================

CREATE TABLE access_request (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code            VARCHAR(80),
    request_type            VARCHAR(20) NOT NULL,
    status                  VARCHAR(40) NOT NULL,
    requester_user_id       BIGINT      NOT NULL,
    requester_unit_id       BIGINT,
    requester_department_id BIGINT,
    shift_no                INT,
    access_no               INT,
    system_id               BIGINT,
    database_id             BIGINT,
    start_time              TIMESTAMP,
    end_time                TIMESTAMP,
    expected_execution_date TIMESTAMP,
    reason                  VARCHAR(2000),
    receiver_user_id        BIGINT,
    handover_manager_id     BIGINT,
    receiver_manager_id     BIGINT,
    source_request_id       BIGINT,
    current_actor_type      VARCHAR(20),
    current_actor_id        BIGINT,
    current_actor_role      VARCHAR(50),
    current_step_code       VARCHAR(60),
    current_unit_id         BIGINT,
    owner_unit_id           BIGINT,
    owner_db_unit_id        BIGINT,
    at_requester_phase      BOOLEAN DEFAULT TRUE,
    created_at              TIMESTAMP,
    submitted_at            TIMESTAMP,
    approved_at             TIMESTAMP,
    completed_at            TIMESTAMP,
    cancelled_at            TIMESTAMP,
    sub_type                VARCHAR(30),
    content_hash            VARCHAR(64),
    CONSTRAINT uk_request_code UNIQUE (request_code)
);

CREATE TABLE request_detail (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         BIGINT NOT NULL,
    system_id          BIGINT,
    database_id        BIGINT,
    object_owner       VARCHAR(100),
    object_name        VARCHAR(200),
    object_type        VARCHAR(30),
    target_user_id     BIGINT,
    account_owner_name VARCHAR(200),
    account_type       VARCHAR(30),
    account_action     VARCHAR(30),
    access_rights      VARCHAR(500),
    query_all          BOOLEAN DEFAULT FALSE,
    scope              VARCHAR(200),
    purpose            VARCHAR(1000),
    detail_data        CLOB
);

CREATE TABLE request_signature (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         BIGINT NOT NULL,
    detail_id          BIGINT,
    signer_user_id     BIGINT NOT NULL,
    signer_role_code   VARCHAR(50),
    signing_scope      VARCHAR(20),
    otp_transaction_id BIGINT,
    signed_at          TIMESTAMP,
    signature_image_id BIGINT,
    result             VARCHAR(20)
);

CREATE TABLE request_script_file (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   BIGINT       NOT NULL,
    detail_id    BIGINT,
    file_name    VARCHAR(255) NOT NULL,
    file_path    VARCHAR(500),
    file_content BLOB,
    checksum     VARCHAR(200),
    uploaded_by  BIGINT,
    uploaded_at  TIMESTAMP
);

-- ============================ WORKFLOW / LOG ============================

CREATE TABLE workflow_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      BIGINT NOT NULL,
    step_code       VARCHAR(60),
    from_status     VARCHAR(40),
    to_status       VARCHAR(40),
    actor_user_id   BIGINT,
    actor_role_code VARCHAR(50),
    action          VARCHAR(20),
    comment_text    VARCHAR(2000),
    processed_at    TIMESTAMP
);

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100),
    role_code   VARCHAR(50),
    action      VARCHAR(80),
    entity_type VARCHAR(80),
    entity_id   BIGINT,
    detail      VARCHAR(2000),
    created_at  TIMESTAMP
);

CREATE TABLE login_log (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(100),
    success    BOOLEAN NOT NULL,
    message    VARCHAR(300),
    ip_address VARCHAR(60),
    logged_at  TIMESTAMP
);

CREATE TABLE otp_transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(100),
    purpose     VARCHAR(60),
    request_id  BIGINT,
    result      VARCHAR(20),
    verified_at TIMESTAMP
);

CREATE TABLE email_queue (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_address  VARCHAR(300) NOT NULL,
    subject     VARCHAR(300),
    body        CLOB,
    request_id  BIGINT,
    event_type  VARCHAR(60),
    status      VARCHAR(20) DEFAULT 'PENDING',
    retry_count INT DEFAULT 0,
    last_error  VARCHAR(1000),
    created_at  TIMESTAMP,
    sent_at     TIMESTAMP
);

CREATE TABLE emergency_completion_link (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergency_request_id  BIGINT NOT NULL,
    completion_request_id BIGINT NOT NULL,
    created_at            TIMESTAMP
);

CREATE TABLE work_log_07 (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      BIGINT,
    actor_user_id   BIGINT,
    actor_role_code VARCHAR(50),
    work_content    VARCHAR(2000),
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    created_at      TIMESTAMP
);

-- ============================ V4: pre_registration_request (thay access_registration) ============================

CREATE TABLE pre_registration_request (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    unit_code            VARCHAR(50),
    register_date        DATE NOT NULL,
    shift                INT NOT NULL,
    request_type         VARCHAR(20),
    system_id            BIGINT,
    database_id          BIGINT,
    object_name          VARCHAR(200),
    access_rights        VARCHAR(200),
    signed_at            TIMESTAMP,
    signature_image_id   BIGINT,
    status               VARCHAR(30) DEFAULT 'UNUSED' NOT NULL,
    request_id           BIGINT,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    version              INT DEFAULT 0
);

-- ============================ INDEXES ============================
CREATE INDEX ix_request_requester   ON access_request (requester_user_id);
CREATE INDEX ix_request_type        ON access_request (request_type);
CREATE INDEX ix_request_source      ON access_request (source_request_id);
CREATE INDEX ix_detail_request      ON request_detail (request_id);
CREATE INDEX ix_signature_request   ON request_signature (request_id);
CREATE INDEX ix_history_request     ON workflow_history (request_id);
CREATE INDEX ix_userrole_user       ON user_role (user_id);
CREATE INDEX ix_dbcatalog_system    ON database_catalog (system_id);
CREATE INDEX ix_prereg_user_status  ON pre_registration_request (user_id, status);
CREATE INDEX ix_prereg_unit_date_shift ON pre_registration_request (unit_code, register_date, shift, status);
