-- =====================================================================
-- DDL Oracle day du cho he thong Quan ly truy cap CSDL
-- Doi tuong: Oracle 12c+ (dung IDENTITY column, khop Oracle12cDialect).
-- Chay bang user so huu schema (vd: qltcdb) tren PDB ebankpdb_pt.
-- Kieu cot khop entity JPA:
--   Long -> NUMBER(19,0), Integer -> NUMBER(10,0), boolean -> NUMBER(1,0)
--   String(n) -> VARCHAR2(n CHAR), LocalDateTime -> TIMESTAMP, LocalDate -> DATE
--   @Lob String -> CLOB, @Lob byte[] -> BLOB
-- Khong khai bao FK (ung dung tham chieu bang khoa Long, khong dung @ManyToOne).
-- =====================================================================

-- ============================ DANH MUC ============================

CREATE TABLE unit (
    id     NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR2(50 CHAR)  NOT NULL,
    name   VARCHAR2(200 CHAR) NOT NULL,
    active NUMBER(1,0)        DEFAULT 1 NOT NULL,
    CONSTRAINT uk_unit_code UNIQUE (code)
);

CREATE TABLE department (
    id      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR2(50 CHAR)  NOT NULL,
    name    VARCHAR2(200 CHAR) NOT NULL,
    unit_id NUMBER(19,0)       NOT NULL,
    active  NUMBER(1,0)        DEFAULT 1 NOT NULL
);

CREATE TABLE information_system (
    id                  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR2(50 CHAR)  NOT NULL,
    name                VARCHAR2(200 CHAR) NOT NULL,
    owner_unit_id       NUMBER(19,0),
    owner_department_id NUMBER(19,0),
    active              NUMBER(1,0) DEFAULT 1 NOT NULL,
    CONSTRAINT uk_infosys_code UNIQUE (code)
);

CREATE TABLE database_catalog (
    id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id     NUMBER(19,0)       NOT NULL,
    code          VARCHAR2(50 CHAR)  NOT NULL,
    name          VARCHAR2(200 CHAR) NOT NULL,
    owner_unit_id NUMBER(19,0),
    active        NUMBER(1,0) DEFAULT 1 NOT NULL
);

CREATE TABLE access_right_catalog (
    id     NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code   VARCHAR2(50 CHAR)  NOT NULL,
    name   VARCHAR2(150 CHAR) NOT NULL,
    active NUMBER(1,0) DEFAULT 1 NOT NULL,
    CONSTRAINT uk_right_code UNIQUE (code)
);

CREATE TABLE role (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR2(50 CHAR)  NOT NULL,
    name        VARCHAR2(150 CHAR) NOT NULL,
    description VARCHAR2(300 CHAR),
    CONSTRAINT uk_role_code UNIQUE (code)
);

CREATE TABLE work_shift (
    id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_no   NUMBER(10,0)      NOT NULL,
    name       VARCHAR2(50 CHAR) NOT NULL,
    start_hour NUMBER(10,0)      NOT NULL,
    end_hour   NUMBER(10,0)      NOT NULL,
    label      VARCHAR2(50 CHAR),
    active     NUMBER(1,0) DEFAULT 1 NOT NULL,
    CONSTRAINT uk_shift_no UNIQUE (shift_no)
);

-- ============================ NGUOI DUNG / PHAN QUYEN ============================

CREATE TABLE app_user (
    id                 NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR2(100 CHAR) NOT NULL,
    full_name          VARCHAR2(200 CHAR),
    mobile             VARCHAR2(30 CHAR),
    email              VARCHAR2(200 CHAR),
    unit_id            NUMBER(19,0),
    department_id      NUMBER(19,0),
    signature_image_id NUMBER(19,0),
    status             VARCHAR2(20 CHAR) DEFAULT 'ACTIVE',
    CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE user_role (
    id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER(19,0) NOT NULL,
    role_id       NUMBER(19,0) NOT NULL,
    unit_id       NUMBER(19,0),
    department_id NUMBER(19,0),
    system_id     NUMBER(19,0),
    database_id   NUMBER(19,0),
    active        NUMBER(1,0) DEFAULT 1 NOT NULL
    --CONSTRAINT "SYS_C0053195" PRIMARY KEY ("ID", "USER_ID", "ROLE_ID")
);

CREATE TABLE signature_image (
    id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(19,0),
    content_type VARCHAR2(100 CHAR),
    data         BLOB
);

CREATE TABLE user_totp (
    id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      NUMBER(19,0)      NOT NULL,
    secret       VARCHAR2(64 CHAR) NOT NULL,
    enabled      NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at   TIMESTAMP,
    confirmed_at TIMESTAMP,
    CONSTRAINT uk_totp_user UNIQUE (user_id)
);

-- ============================ PHIEU YEU CAU ============================

CREATE TABLE access_request (
    id                      NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code            VARCHAR2(80 CHAR),
    request_type            VARCHAR2(20 CHAR) NOT NULL,
    status                  VARCHAR2(40 CHAR) NOT NULL,
    requester_user_id       NUMBER(19,0)      NOT NULL,
    requester_unit_id       NUMBER(19,0),
    requester_department_id NUMBER(19,0),
    shift_no                NUMBER(10,0),
    access_no               NUMBER(10,0),
    system_id               NUMBER(19,0),
    database_id             NUMBER(19,0),
    start_time              TIMESTAMP,
    end_time                TIMESTAMP,
    expected_execution_date TIMESTAMP,
    reason                  VARCHAR2(2000 CHAR),
    receiver_user_id        NUMBER(19,0),
    handover_manager_id     NUMBER(19,0),
    receiver_manager_id     NUMBER(19,0),
    source_request_id       NUMBER(19,0),
    current_actor_type      VARCHAR2(20 CHAR),
    current_actor_id        NUMBER(19,0),
    current_actor_role      VARCHAR2(50 CHAR),
    current_step_code       VARCHAR2(60 CHAR),
    current_unit_id         NUMBER(19,0),
    owner_unit_id           NUMBER(19,0),
    owner_db_unit_id        NUMBER(19,0),
    at_requester_phase      NUMBER(1,0) DEFAULT 1,
    created_at              TIMESTAMP,
    submitted_at            TIMESTAMP,
    approved_at             TIMESTAMP,
    completed_at            TIMESTAMP,
    cancelled_at            TIMESTAMP,
    CONSTRAINT uk_request_code UNIQUE (request_code)
);

CREATE TABLE request_detail (
    id                 NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         NUMBER(19,0) NOT NULL,
    system_id          NUMBER(19,0),
    database_id        NUMBER(19,0),
    object_owner       VARCHAR2(100 CHAR),
    object_name        VARCHAR2(200 CHAR),
    object_type        VARCHAR2(30 CHAR),
    target_user_id     NUMBER(19,0),
    account_owner_name VARCHAR2(200 CHAR),
    account_type       VARCHAR2(30 CHAR),
    account_action     VARCHAR2(30 CHAR),
    access_rights      VARCHAR2(500 CHAR),
    query_all          NUMBER(1,0) DEFAULT 0,
    scope              VARCHAR2(200 CHAR),
    purpose            VARCHAR2(1000 CHAR),
    detail_data        CLOB
);

CREATE TABLE request_signature (
    id                 NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         NUMBER(19,0) NOT NULL,
    detail_id          NUMBER(19,0),
    signer_user_id     NUMBER(19,0) NOT NULL,
    signer_role_code   VARCHAR2(50 CHAR),
    signing_scope      VARCHAR2(20 CHAR),
    otp_transaction_id NUMBER(19,0),
    signed_at          TIMESTAMP,
    signature_image_id NUMBER(19,0),
    result             VARCHAR2(20 CHAR)
);

CREATE TABLE request_script_file (
    id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   NUMBER(19,0)       NOT NULL,
    detail_id    NUMBER(19,0),
    file_name    VARCHAR2(255 CHAR) NOT NULL,
    file_path    VARCHAR2(500 CHAR),
    file_content BLOB,
    checksum     VARCHAR2(200 CHAR),
    uploaded_by  NUMBER(19,0),
    uploaded_at  TIMESTAMP
);

-- ============================ WORKFLOW / LOG ============================

CREATE TABLE workflow_history (
    id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      NUMBER(19,0) NOT NULL,
    step_code       VARCHAR2(60 CHAR),
    from_status     VARCHAR2(40 CHAR),
    to_status       VARCHAR2(40 CHAR),
    actor_user_id   NUMBER(19,0),
    actor_role_code VARCHAR2(50 CHAR),
    action          VARCHAR2(20 CHAR),
    comment_text    VARCHAR2(2000 CHAR),
    processed_at    TIMESTAMP
);

CREATE TABLE audit_log (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(100 CHAR),
    role_code   VARCHAR2(50 CHAR),
    action      VARCHAR2(80 CHAR),
    entity_type VARCHAR2(80 CHAR),
    entity_id   NUMBER(19,0),
    detail      VARCHAR2(2000 CHAR),
    created_at  TIMESTAMP
);

CREATE TABLE login_log (
    id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR2(100 CHAR),
    success    NUMBER(1,0) NOT NULL,
    message    VARCHAR2(300 CHAR),
    ip_address VARCHAR2(60 CHAR),
    logged_at  TIMESTAMP
);

CREATE TABLE otp_transaction (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(100 CHAR),
    purpose     VARCHAR2(60 CHAR),
    request_id  NUMBER(19,0),
    result      VARCHAR2(20 CHAR),
    verified_at TIMESTAMP
);

CREATE TABLE email_queue (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_address  VARCHAR2(300 CHAR) NOT NULL,
    subject     VARCHAR2(300 CHAR),
    body        CLOB,
    request_id  NUMBER(19,0),
    event_type  VARCHAR2(60 CHAR),
    status      VARCHAR2(20 CHAR) DEFAULT 'PENDING',
    retry_count NUMBER(10,0) DEFAULT 0,
    last_error  VARCHAR2(1000 CHAR),
    created_at  TIMESTAMP,
    sent_at     TIMESTAMP
);

CREATE TABLE emergency_completion_link (
    id                    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergency_request_id  NUMBER(19,0) NOT NULL,
    completion_request_id NUMBER(19,0) NOT NULL,
    created_at            TIMESTAMP
);

CREATE TABLE work_log_07 (
    id              NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      NUMBER(19,0),
    actor_user_id   NUMBER(19,0),
    actor_role_code VARCHAR2(50 CHAR),
    work_content    VARCHAR2(2000 CHAR),
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    created_at      TIMESTAMP
);

CREATE TABLE access_registration (
    id                NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id NUMBER(19,0) NOT NULL,
    system_id         NUMBER(19,0),
    database_id       NUMBER(19,0),
    object_name       VARCHAR2(200 CHAR),
    access_rights     VARCHAR2(200 CHAR),
    shift_no          NUMBER(10,0),
    from_date         DATE,
    to_date           DATE,
    signed            NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at        TIMESTAMP
);

-- ============================ INDEX phu tro (tuy chon) ============================
CREATE INDEX ix_request_requester   ON access_request (requester_user_id);
CREATE INDEX ix_request_type        ON access_request (request_type);
CREATE INDEX ix_request_source      ON access_request (source_request_id);
CREATE INDEX ix_detail_request      ON request_detail (request_id);
CREATE INDEX ix_signature_request   ON request_signature (request_id);
CREATE INDEX ix_history_request     ON workflow_history (request_id);
CREATE INDEX ix_userrole_user       ON user_role (user_id);
CREATE INDEX ix_dbcatalog_system    ON database_catalog (system_id);

COMMIT;
