-- =====================================================================
-- V4: Thay thế bảng access_registration bằng pre_registration_request
-- Bảng cũ chỉ lưu thông tin đăng ký đơn giản; bảng mới hỗ trợ đầy đủ
-- lifecycle (status tracking, OTP signing, liên kết phiếu 01-YCTC).
-- =====================================================================

-- 1. Xóa bảng cũ
DROP TABLE access_registration CASCADE CONSTRAINTS PURGE;

-- 2. Tạo bảng mới
CREATE TABLE pre_registration_request (
    id                   NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              NUMBER(19,0) NOT NULL,
    unit_code            VARCHAR2(50 CHAR),
    register_date        DATE NOT NULL,
    shift                NUMBER(10,0) NOT NULL,
    request_type         VARCHAR2(20 CHAR),
    system_id            NUMBER(19,0),
    database_id          NUMBER(19,0),
    object_name          VARCHAR2(200 CHAR),
    access_rights        VARCHAR2(200 CHAR),
    signed_at            TIMESTAMP,
    signature_image_id   NUMBER(19,0),
    status               VARCHAR2(30 CHAR) DEFAULT 'UNUSED' NOT NULL,
    request_id           NUMBER(19,0),
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    version              NUMBER(10,0) DEFAULT 0,
    CONSTRAINT fk_prereg_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_prereg_request FOREIGN KEY (request_id) REFERENCES access_request(id)
);

-- 3. Indexes
CREATE INDEX ix_prereg_user_status ON pre_registration_request (user_id, status);
CREATE INDEX ix_prereg_unit_date_shift ON pre_registration_request (unit_code, register_date, shift, status);
